USE [master]
GO

/****** Object:  Database [ControlHoras]    Script Date: 16/08/2016 14:19:52 ******/
CREATE DATABASE [ControlHoras]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ControlHoras', FILENAME = N'D:\Data\ControlHoras.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ControlHoras_log', FILENAME = N'D:\Data\ControlHoras_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ControlHoras] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ControlHoras].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ControlHoras] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ControlHoras] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ControlHoras] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ControlHoras] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ControlHoras] SET ARITHABORT OFF 
GO

ALTER DATABASE [ControlHoras] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ControlHoras] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ControlHoras] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ControlHoras] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ControlHoras] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ControlHoras] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ControlHoras] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ControlHoras] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ControlHoras] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ControlHoras] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ControlHoras] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ControlHoras] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ControlHoras] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ControlHoras] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ControlHoras] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ControlHoras] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ControlHoras] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ControlHoras] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ControlHoras] SET RECOVERY FULL 
GO

ALTER DATABASE [ControlHoras] SET  MULTI_USER 
GO

ALTER DATABASE [ControlHoras] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ControlHoras] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ControlHoras] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ControlHoras] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ControlHoras] SET  READ_WRITE 
GO

